import Head from 'next/head'
import Link from 'next/link'
import React, { useState } from "react";
import dynamic from "next/dynamic";
import { useMediaQuery } from 'react-responsive';

const Header = dynamic(() => import("./header"));
let ItemsFav = dynamic(() => import("./items-favoritos"));
let Items= dynamic(() => import("./items"));

export default function ListaProductos(countProductes, Tipo) {
  const isMobile = useMediaQuery({ query: `(max-width: 760px)` });
  let [pagina, setPagina] = useState(1)
  let paginas = [];
  let numProductos = isMobile ? 6 : 12;
  let firstNumber = Math.min((pagina-3 < 1 ? 1 : pagina-3), Math.ceil(countProductes.countProductes/numProductos-7));
  let numeroPaginas = Math.min(8, Math.ceil(countProductes.countProductes/numProductos));

  if(firstNumber < 1){
    firstNumber = 1;
  }

  for(var i = firstNumber; i < firstNumber+numeroPaginas;i++){
    paginas.push(i)
  }

  function Check(num){
    if(num == pagina){
      return 'active';
    }else{
      return '';
    }
  }

  function CheckArrow(direccion){
    if(direccion == 'right'){
      if(pagina>countProductes.countProductes/numProductos-5){
        return 'invisible'
      }else{
        return '';
      }
    }else if(direccion == 'left'){
      if(pagina<5){
        return 'invisible'
      }else{
        return '';
      }
    }
  }  
    return (
      <>
        <Head>
          <title>KaveHome.com - Muebles y decoración | Kave Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
  
        <main>
          <Header/>
          <div className="center-div">
            <h2>{countProductes.Tipo}</h2>
            <h3>Lorem ipsum dolor sit amet</h3>
          </div>
          {countProductes.Tipo == "Lista de Favoritos" ? (
            <ItemsFav min={(pagina-1)*numProductos} max={pagina*numProductos-1}/>)
            : (<Items min={(pagina-1)*numProductos} max={pagina*numProductos-1}/>)}
          
        </main>
        <footer>
          <Link key="aleft" href={''}><a onClick={()=>setPagina(pagina-1)} className={CheckArrow('left')}>&lsaquo;</a></Link>
          {paginas.map((page, index)=> (
              <Link key={index} href={''}><a key={index} onClick={()=>setPagina(page)} className={Check(page)}>{page}</a></Link>
            ))}
          <Link key="aright" href={''}><a onClick={()=>setPagina(pagina+1)} className={CheckArrow('right')}>&rsaquo;</a></Link>
        </footer>
      </>
    )
  }